vim.keymap.set("n", "<leader>la", vim.lsp.buf.code_action, { desc = "Lsp buf code_action" })
vim.keymap.set("n", "<leader>lr", vim.lsp.buf.rename, { desc = "Lsp buf rename" })
vim.keymap.set("n", "<leader>gD", vim.lsp.buf.declaration, { desc = "Lsp buf declaration" })
vim.keymap.set("n", "<leader>gd", vim.lsp.buf.definition, { desc = "Lsp buf definition" })
vim.keymap.set("n", "<leader>gr", vim.lsp.buf.references, { desc = "Lsp buf references" })
